### ISSUE TITLE
Alert from Vanillafix about Prospectus

### ISSUE THREAD

**Issue by iamweirdie** [Magneticraft-Team/Magneticraft#171] opened 2019-10-01 15:57 UTC
https://paste.dimdev.org/ocavoyizik.mccrash

It appeared when I used the Prospectus stone prospecting pick.
The game doesn't crash, but I'd thought you want to know.

https://www.curseforge.com/minecraft/mc-mods/prospectus
https://www.curseforge.com/minecraft/mc-mods/vanillafix

i've also alerted the other mod.
https://github.com/cam72cam/Prospectus/issues/8

**Comment by cout970** [comment] 2019-10-12 09:57
Prospectus is passing a null value to the parameter target which is marked as NonNull by default, so the problem is from Prospectus not my mod.

**Closed as completed by cout970** 2019-10-12 09:57 UTC
